[font]
size = 15.3

[font.offset]
x = 1
y = 6

[font.glyph_offset]
x = 1
y = 4

[font.normal]
family = "Agave S"
style = "Regular"

[font.bold]
style = "Bold"

[font.italic]
style = "Regular Italic"

[font.bold_italic]
style = "Bold Italic"
