[font]
size = 12.8

[font.offset]
x = 1
y = 2

[font.glyph_offset]
y = 1

[font.normal]
family = "JetBrains Mono NL"
style = "Medium"

[font.bold]
style = "Bold"

[font.italic]
style = "Regular Italic"

[font.bold_italic]
style = "Bold Italic"
