# julia
export JULIA_PROJECT="@."
export JULIA_DEPOT_PATH="${HOME}/Library/Julia"

# rust
export CARGO_HOME="${HOME}/Library/Rust"
export RUSTUP_HOME="${HOME}/Library/Rust/toolchains"
export PATH="${PATH}:${CARGO_HOME}/bin"

# python
export PYTHONPATH="${PYTHONPATH}:${HOME}/Library/Python"

export IPYTHONDIR="${HOME}/Library/Python/preferences/ipython"
export MPLCONFIGDIR="${HOME}/Library/Python/preferences/matplotlib"
export JUPYTER_CONFIG_DIR="${HOME}/Library/Python/preferences/jupyter"

# export PIP_TARGET=/opt/homebrew/site-packages
# export DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH}:/opt/pkg/lib"

# brew
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_AUTOREMOVE=1
export HOMEBREW_CASK_OPTS="--appdir=/Applications --fontdir=/Library/Fonts"
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_EMOJI=1
export HOMEBREW_NO_ENV_HINTS=1
export HOMEBREW_NO_GITHUB_API=1
export HOMEBREW_INSTALL_FROM_API=1

export HOMEBREW_PREFIX="/opt/homebrew";
export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
export HOMEBREW_REPOSITORY="/opt/homebrew";
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";
export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";
