set -g mouse on
set-option -g history-limit 1000000

set -g set-clipboard on
set-option -ag terminal-overrides ",xterm-256color:Ms=\\E]52;c;%p2%s\\7"

set -g default-terminal "xterm-256color"
bind-key -n Home send Escape "OH"
bind-key -n End send Escape "OF"

setw -g mode-keys vi
bind-key / copy-mode \; send-key ?

unbind-key C-b
set-option -g prefix C-F12
bind-key -n C-F12 send-prefix

unbind-key -T copy-mode-vi MouseDragEnd1Pane
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel

# emulate scroll if not supported
bind-key -T root WheelUpPane \
	if-shell -Ft= '#{?mouse_any_flag,1,#{pane_in_mode}}' \
		'send -Mt=' \
		'if-shell -t= "#{?alternate_on,true,false} | grep -q \"#{pane_current_command}\"" \
			"send -t= Up" "copy-mode -et="'

bind-key -T root WheelDownPane \
	if-shell -Ft = '#{?pane_in_mode,1,#{mouse_any_flag}}' \
		'send -Mt=' \
		'if-shell -t= "#{?alternate_on,true,false} | grep -q \"#{pane_current_command}\"" \
			"send -t= Down" "send -Mt="'

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# clock mode
setw -g clock-mode-colour colour1

# pane borders
set -g pane-border-style 'fg=colour1'
set -g pane-active-border-style 'fg=colour3'

# statusbar
set -g base-index 1
set -g status-position top
set -g status-justify left
set -g status-style 'fg=colour1'
set -g status-left ''
# set -g status-right '%Y-%m-%d %H:%M '
set -g status-right '#(pgrep caffeinate > /dev/null || echo "󰒲 ")'
set -g status-right-length 50
set -g status-left-length 10

setw -g window-status-current-style 'fg=colour0 bg=colour1 bold'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=colour1 dim'
setw -g window-status-format ' #I #[fg=colour7]#W #[fg=colour1]#F '

setw -g window-status-bell-style 'fg=colour2 bg=colour1 bold'

# messages
set -g message-style 'fg=colour2 bg=colour16 bold'
